services:
  db:
    image: postgres:16
    container_name: fincontrol-db
    environment:
      POSTGRES_DB: fincontroldb
      POSTGRES_USER: fincontrol
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fincontrol -d fincontroldb"]
      interval: 5s
      retries: 10

volumes:
  pgdata: